### PR TITLE
Multiline comments and full operator support

### PR DESCRIPTION
**Pull request by eatonphil**
Def make this a separate git repo unless you seriously only want it as a toy. Also, I believe you are trying to recreate the hardest part of lexical analysis... That is, a regex engine.. When I wrote my lexer for hmm... whatever I wrote it for. I used regex to handle the brunt of the work. This will make you code much cleaner and much easier to understand. You see because what you're doing is lexical analysis. However, lexer's don't normally even handle this particular depth of picking at strings. You'll be able to get a lot more power out of using regex to identify tokens. You can build a nice framework around that easily enough that still gets you at something hardcore without chasing after a regex engine... Also, there are some good syntax highlighters out there. I use crayon... I'm not saying this because I'm against learning how things work. But in your blog you mentioned that you didn't want to build a blogging engine because more mature ones exist... That philosophy is a little contrary to what's going on here ;) But anyway, I put in multi-line comments for you. It should work. But I didn't check. Good luck!

### CODE REVIEW

**Comment by cfalk** [comment]
Yeah, as I mentioned in my blog I am planning on making it a separate Repo.
: ) It is nowhere close to complete, haha (it only has the parts of
JavaScript that I've used so far in my blog, haha -- though I appreciate
your additions! Saved me time later. ;) ).

And I actually thought about using Regular Expressions, but I realized that
RegEx is massive overkill for just a simple parser. Especially since I am
only covering half of a language at the moment, haha.
Also, parsing is a more "general" parent term for lexical analysis -- no? ;)

In regards to using something more "mature," this seemed like (and actually
was) a simple enough problem that building a light syntax that did exactly
what I wanted was more time-efficient. Building a blogging engine requires
server-transactions, database management, regular backups, etc. . At least
a few hours of difference, I'd say -- haha! Good point though; you caught
me. ;)

Many thanks, Phil! : )

**Comment by cfalk** [comment]
PS: I'll check your edits and merge your pull next time I post something. : )

**Comment by eatonphil** [comment]
Woah woah woah big guy. PArsing and lexing are entirely different steps. Parsing has to do with syntax and grammar. Lexing has to do tokens. A lexer affirms that all strings conform to a lexicon or token dictionary. A parse affirms that all combinations of tokens strictly conform to a grammar, a syntax. So now this is definitely not a parser because nowhere do you care about the grammar or syntax of javascript - ie HOW you use the keywords and junk that the lexicon contains. It is also not more of a regex engine than a lexer because the primary focus is in identifying lexemes/tokens and not making sure that only lexemes from a dictionary are allowed. But I still promise yiu that a lexer with the js regex engine would be much more succinct

**Comment by cfalk** [comment]
Derp, you are totally right about parsing/lexing. My bad. I blame lack of
coffee today -- I didn't realize what I was writing XD. And you are
probably right that it would be more succinct; I actually have an idea
about how expand this easily with RegEx (based on my previous blog post).
Next time! Thanks for catching my tongue! ;)

**Comment by eatonphil** [comment]
Haha no worries. It took me forever to get it and everyone always mixes them up. But yeah give it a shot! You'd be able to do much more powerful and  interesting this here if you chose to go with regex. I can send you the one I wrote in python sometieme if youd like to give you an idea

**Comment by cfalk** [comment]
I have a pretty good idea how to do it by dynamically constructing the
regular expression, but I'd love to see your Python work. : D Feel free to
PM me the link. : )

**Pull request closed without merging**
